// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import HelloController from './hello_controller';
application.register('hello', HelloController);

import WordCountController from './word_count_controller';
application.register('word-count', WordCountController);
